### ISSUE TITLE
Use ElasticSearch via Spring Boot and Spring Data

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/autoindex#2]
Follow this tutorial https://www.dinkla.net/de/programming/spring-boot-elasticsearch-doc.html

More information can be found here
https://github.com/spring-projects/spring-data-elasticsearch
http://www.baeldung.com/spring-data-elasticsearch-tutorial

Use as few code as possible

**Comment by Kunal-Jha** [comment]
Completed
